# Generated by Django 5.2.8 on 2025-12-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='set_date',
            field=models.IntegerField(),
        ),
    ]
