# Generated by Django 5.2.8 on 2025-12-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_set_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='set_date',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
